data <- read.csv("household_power_consumption.txt", sep=";")
crp <- subset(data, (strptime(Date,format="%d/%m/%Y") == "2007-02-01 PST" | strptime(Date,format="%d/%m/%Y") == "2007-02-02 PST"))
full <- paste(crp$Date,crp$Time)
plot(strptime(full,format="%d/%m/%Y %H:%M:%S"),as.numeric(crp$Sub_metering_1),xlab="",ylab="Energy sub metering",type="l")
lines(strptime(full,format="%d/%m/%Y %H:%M:%S"),as.numeric(crp$Sub_metering_2),col="red")
lines(strptime(full,format="%d/%m/%Y %H:%M:%S"),as.numeric(crp$Sub_metering_3),col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.copy(png,file="plot3.png")
dev.off()